# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: GPL-3.0-or-later

[tool.bumpversion]
current_version = "0.2.2"

[[tool.bumpversion.files]]
filename = "docs/man/man1/gb3sum.1.adoc"

[[tool.bumpversion.files]]
filename = "testdata/version.ct"

[[tool.bumpversion.files]]
filename = "version.go"
